# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
        # aws-sdk has many minor version updates, ignore them.
        # keep patch updates as if aws ever releases one, it's because there's a serious issue with the minor version
      - dependency-name: "@aws-sdk*"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "eslint*"
    groups:
      aws-sdk:
        patterns:
        - "@aws-sdk*"
      production-dependencies:
        dependency-type: "production"
        exclude-patterns:
        - "@aws-sdk*"
      development-dependencies:
        dependency-type: "development"
