---
defaults:
  settings:
    region: ap-southeast-2
    timezone: Australia/Melbourne
    timezoneTag: Timezone
    organizationRoleName: AWSOrganizationsReadOnly
    revolverRoleName: ssPowerCycle
    saveResources: resources.json
    localResourcesFile: local-resources.json
    audit:
      console:
      csv:
        file: "audit.csv"
        append: true
    logResources: true

  drivers:
    - name: ec2
      active: true
      pretend: false
    - name: ebs
    - name: snapshot
    - name: rdsInstance
    - name: rdsCluster

  plugins:
    powercycleCentral:
      active: true
      configs:
        - parser: strict
          availabilityTag: Schedule
          availabilityTagPriority: 5
          matchers:
            - name: default tagged schedule
              filter:
                - tag: ["CostCentre||value|1234", "CostCentre|4567"]
                - type: ec2
                - resource: "Placement.AvailabilityZone||contains|ap-southeast"
              schedule: 24x7
              priority: 1
            - name: no large instances
              filter:
                or:
                  - resource:
                      path: "InstanceType"
                      regexp: "\\.\\d{0,2}x?large"
                  - resource:
                      path: "InstanceType"
                      regexp: "\\.metal\\-\\d{1,2}xl"
              schedule: "0x7"
              priority: 20
            - name: within australia
              filter:
                resource:
                  path: "Placement.AvailabilityZone | contains(@, 'ap-southeast')"
                  value: true
              schedule: 24x5
              priority: 10
    powercycle:
      active: true
      configs:
        - tagging: strict
          availabilityTag: Schedule
    validateTags:
      active: true
      configs:
        - tag: Name
          tagMissing:
            - copyFromParent
          onlyResourceTypes:
            - ebs
            - snapshot
          tagNotMatch: []
        - tag: Name
          tagMissing:
            - warn
          onlyResourceTypes:
            - ec2
          tagNotMatch: []
        - tag: Schedule
          tagMissing:
            - setDefault: 24x7
          onlyResourceTypes:
            - ec2
            - rdsInstance
            - rdsCluster
          tagNotMatch: []

organizations:
  - accountId: "000000000000"
    settings:
      region: ap-southeast-2
      name: eh-global-apse2
  - accountId: "111111111111"
    settings:
      region: eu-west-1
      name: eh-global-euw1

accounts:
  includeList:
    - accountId: "222222222222"
      settings:
        name: whatdev
        revolverRoleName: powerCycleRole
  excludeList:
    - accountId: "333333333333"
      settings:
        name: whatprod
