---
defaults:
  settings:
    region: ap-southeast-2
    timezone: Australia/Melbourne
    timezoneTag: Timezone
    organizationRoleName: AWSOrganizationsReadOnly
    revolverRoleName: ssPowerCycle
    saveResources: resources.json

  drivers:
    - name: ec2
      active: true
      pretend: false
    - name: ebs
      active: true
      pretend: false
    - name: snapshot
      active: true
      pretend: false
    - name: rdsInstance
      active: true
      pretend: false
    - name: rdsCluster
      active: true
      pretend: false

  plugins:
    powercycle:
      active: true
      configs:
        - tagging: strict
          availabilityTag: Schedule
    validateTags:
      active: true
      configs:
        -
          tag: Name
          tagMissing:
            - copyFromParent
          onlyResourceTypes:
            - ebs
            - snapshot
          tagNotMatch: []
        -
          tag: Name
          tagMissing:
            - warn
          onlyResourceTypes:
            - ec2
          tagNotMatch: []
        -
          tag: Schedule
          tagMissing:
            - setDefault: 24x7
          onlyResourceTypes:
            - ec2
            - rdsInstance
            - rdsCluster
          tagNotMatch: []

organizations:
  - accountId: 000000000000
    settings:
      region: ap-southeast-2
      name: eh-global-apse2
  - accountId: 111111111111
    settings:
      region: eu-west-1
      name: eh-global-euw1

accounts:
  includeList:
    - accountId: 222222222222
      settings:
        name: whatdev
  excludeList:
    - accountId: 333333333333
      settings:
        name: whatprod
