---
defaults:
  settings:
    region: ap-southeast-2
    timezone: Australia/Melbourne
    timezone_tag: Timezone
    organization_role_name: AWSOrganizationsReadOnly
    revolver_role_name: ssPowerCycle

  drivers:
    - name: ec2
      active: true
      pretend: false
    - name: ebs
      active: true
      pretend: false
    - name: snapshot
      active: true
      pretend: false
    - name: rdsInstance
      active: true
      pretend: false
    - name: rdsMultiAz
      active: true
      pretend: false
    - name: rdsMultiAzSnapshot
      active: true
      pretend: false
    - name: rdsCluster
      active: true
      pretend: false
    - name: rdsClusterSnapshot
      active: true
      pretend: false

  plugins:
    powercycle:
      active: true
      configs:
        - tagging: strict
          availability_tag: Schedule
    validateTags:
      active: true
      configs:
        -
          tag: Name
          tag_missing:
            - warn
          tag_not_match: []
        -
          tag: Schedule
          tag_missing:
            - warn
          tag_not_match: []
    restoreRdsSg:
      active: true
      configs: []

organizations: []

accounts:
  include_list:
    - account_id: "A00000000000"
      settings:
        name: whatdev

  exclude_list: []
