name: Run tests
on:
  pull_request:
    branches: [main, develop]

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  mocha-tests:
    name: Run Mocha tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: https://npm.pkg.github.com
      - run: npm ci
      - run: npm run build
      - run: npm test
  lint:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: https://npm.pkg.github.com
      - run: npm ci
      - run: npm run lint
